# See here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
forbidden:
  - COD_BUCKET
  - LAVA_BUCKET
  - PUFFERFISH_BUCKET
  - SALMON_BUCKET
  - TROPICAL_FISH_BUCKET
  - WATER_BUCKET
